services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=db_livraria'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=admin'
    ports:
      - 3306:3306
